version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: lab-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-db
    networks:
      - production-network
    ports:
      - "5432:5432"
networks:
  production-network:
    driver: bridge