version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: lab-api-db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - production-network
    ports:
      - "5432:5432"
  api:
    image: labestudo/api:latest
    container_name: lab-api
    networks:
      - production-network
    ports:
      - "8080:8080"
    environment:
      - "POSTGRES_URL=lab-api-db"
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
      - MAIL_USER 
      - MAIL_PASS 
networks:
  production-network:
    driver: bridge